apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: bluegreen-vs
spec:
  host: dot.demo.ocpcluster.gabledemo.com
  upstreams:
  - name: greendot
    service: greendot-svc
    port: 80
  - name: bluedot
    service: bluedot-svc
    port: 80
  - name: reddot
    service: reddot-svc
    port: 80
  routes:
  - path: /
    matches:
    - conditions:
      - header: version
        value: green
      action:
        pass: greendot
    - conditions:
      - header: version
        value: red
      action:
        pass: reddot
    action:
      pass: bluedot