apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: bluegreen-vs
spec:
  host: dot.demo.ocpcluster.gabledemo.com
  upstreams:
  - name: greendot
    service: greendot-svc
    port: 80
  - name: bluedot
    service: bluedot-svc
    port: 80
  - name: reddot
    service: reddot-svc
    port: 80
  routes:
  - path: /
    errorPages:
    - codes: [502]
      return:
         code: 200
         body: "<center><h1>oops! We will be back shortly!</h1></center>"
    action:
       proxy:
          upstream: bluedot
