apiVersion: apps/v1
kind: Deployment
metadata:
  name: dot-red
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddot
  template:
    metadata:
      labels:
        app: reddot
    spec:
      containers:
      - name: reddot
        image: ratthanin/reddot:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reddot-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: reddot